---
# tasks file for apigee-opdk-setup-postgres-config
- block:

  - name: Set permissions on pgdata folder
    file:
      path: '{{ apigee_postgresql_data_dir }}'
      owner: '{{ opdk_user_name }}'
      group: '{{ opdk_group_name }}'
      mode: 0700
      state: directory

  - name: Remove pgdata folder for 4.16.09
    file:
      path: '{{ apigee_postgresql_data_dir }}'
      state: absent
    when: clear_pgdata | default(False)

  become: true
